# Generated by Django 4.1.6 on 2023-02-22 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='NAME', max_length=256)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_column='CREA_DT')),
                ('updated_time', models.DateTimeField(auto_now=True, db_column='UPDT_DT')),
                ('user', models.OneToOneField(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='NAME', max_length=256)),
                ('latitude', models.FloatField(db_column='LAT')),
                ('longitude', models.FloatField(db_column='LNG')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_column='CREA_DT')),
                ('updated_time', models.DateTimeField(auto_now=True, db_column='UPDT_DT')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='api.profile')),
            ],
        ),
    ]
