# Generated by Django 4.1.6 on 2023-02-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='place',
            table='place',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
