# Generated by Django 4.1.7 on 2023-02-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_kakaoplace_place_contents_alter_place_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kakaoplace',
            old_name='address_id',
            new_name='id',
        ),
    ]
