# Generated by Django 4.1.7 on 2023-02-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_address_id_kakaoplace_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='kakao_address',
            new_name='kakao_place',
        ),
    ]
