# Generated by Django 4.1.7 on 2023-02-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_kakao_address_place_kakao_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='score',
            field=models.IntegerField(choices=[(1, 'BAD'), (5, 'GOOD')], default=5),
        ),
    ]
